name: counter_elementary
description: Implementation of the counter on Elementary.


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"


dependencies:
  cupertino_icons: ^1.0.2
  dart_code_metrics: ^4.14.0
  elementary: ^1.3.0
  flutter:
    sdk: flutter
  provider: ^6.0.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  surf_lint_rules: ^1.5.0


flutter:
  uses-material-design: true