# This is a basic workflow to help you get started with Actions

name: Analysis

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Install Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      
      - name: Install dependencies
        run: flutter pub get
          
      - name: Run analyzer
        run: flutter analyze --fatal-warnings --fatal-infos .

      - name: Run formatter
        run: flutter format --set-exit-if-changed .
        

